### ISSUE TITLE
New version of XMLKit breaks compilation.

### ISSUE THREAD

**Issue by vcanuel** [daltoniam/DCXMPP#1]
Hi @daltoniam,

I would like to build this project but the new XMLKit dependency (in swift) seems not compatible with DCXMPP (No XMLElement, method elementWithName is missing, etc.).

Could you restore the old version in a separate branch by any chance ?

Thanks,

Vincent.

**Comment by daltoniam** [comment]
Hi @vcanuel,
The old XMLKit dependency can be found here:
https://github.com/daltoniam/XMLKit-objc

I intended to update both with the new name, but I didn't realize anyone still used either of those repos 😄. I'll try and update the name in the next few days to fix compilation.

**Comment by vcanuel** [comment]
nice thanks :)
